from app import create_app
from app.extensions import db
from app.models.worker import Worker
from app.models.user import User
from app.models.schedule import ScheduleEntry
from app.models.attendance import AttendanceRecord
from sqlalchemy import text

app = create_app()

RAW_DATA = """
[JEFATURA CCO, PLANTA EXTERNA, ENCARGADOS]
LS DULANTO LI, ALEX JOSE MELCHOR
LS SIFUENTES DAVILA, HOOVER
LS ZAVALA ACOSTA, JEYSON MARCO
CAS YOTO VIVANCO ROMMEL LUCIO
LS SAINT PERE LA HOZ, ALEJANDRO

[ÁREA DE GESTIÓN DE VIDEO (OBSERVATORIO)]
LS BALLON ACOSTA, FAVIO CLAUDIO
LS ESCALANTE GUITIERREZ JOSE YARICK
LS LULE CHACHAPOYAS, DEYBER
CAS HUAMANI ALATA, CRISTOPHER TERRY
CAS CORDOVA MANCHEGO MILAGROS VIVIANA

[SUPERVISORES]
CAS ORMEÑO MENDOZA, WILLY ALBERTO -- GRUPO 1
CAS IÑAPE HIDALGO ARTURO            -- GRUPO 2
CAS BELLIDO TOLEDO, JORGE ADALBERTO - GRUPO 3

[GRUPO 1 - CCO]
CAS VASQUEZ ESTRELLA MARICELA
CAS CLAUSEY BAUTISTA ALVARO JORGE
LS MAQUERA VELASQUEZ DINA EULALIA
LS EDUARDO ISAC CASTILLO ESPONOZA
LS SHARON BRIGITTE RENTERIA COBEÑAZ
LS GODINES AGUILAR ANDREA
LS ANGULO ZAMBRANO ABNER DENNIS
LS COLLAN ALVAREZ JUAN CARLOS J.
LS ESPINO HERRERA WILLIAM
LS CAMARO PÉREZ DAYANA NICOL
LS MONTERO MENA CYNTHIA SHERLEY
CAS IGLESIAS CORONIL ANGELY VANESSA
CAS CUYA SIMPE BRIAN JESUS
LS MEDINA TASAYCO GALENO SAUL
LS GARCIA AGUILA FERMINA PATRICIA
LS GOMEZ CORAC LUIS ANGEL
LS CENEPO MARIN GRECIA
LS ALHUAY HUAMANI FIORELLA
LS SALAZAR TORRES LALY ELIZABETH JHANNY
LS MESCCO HUACAC KARINA CAROLINA
LS MENDOZA CANQUI ALLAN JOE
LS QUISPE HERNANDEZ MARIA JULIA
LS SALAS PEREZ LADY LAURA
LS YACORI YAMILE CORTEZ GAMARRA
LS QUISPE COVEÑAS JANET AGRIPINA
CAS JARAMILLO MORALES JOE
LS MENDOZA CAHASA ROSINA DEL PILAR
CAS DELGADO RODRIGUEZ RUTH LIBERT
CAS SEGUNDO HURTADO CATHERINE
LS QUISPE TORIBIO XIOMARA NICOLE
LS LUYO CASTRO KEYLA
LS CAYLLAHUA NEYRA MIRIAM NOEMI
LS DE LA CRUZ CHIPA JUAN JOSE
LS LEIDDY BRENDA LOZADA DELGADO
LS YUMI SHAELA ARIAS REFULIO
LS KJURO HERMOZA RUTH EVELIN
LS EDUARDO HECTOR CORONEL TULLUME
LS STACI MELISSA OVALLE CUZCANO
LS NIXON ALEJANDRO QUISPE GALVEZ
LS LEONELA REYES YACSAVILCA

[GRUPO 1 - CCO - ALFA (GPS, RADIO)]
CAS HUAMAN MERCADO FLOR DE  MARIA
LS ANGULO ROJAS JOSE GUILLERMO

[GRUPO 1 - SCV]
LS CAPARACHIN SOLIS THIAGO
LS SALDAÑA COTRINA JESSICA
CAS MAMANI JUAREZ SILVIA ANGELICA
CAS BENEGAS ALEJANDRO VANESSA
LS SANCHEZ CHINCHAY LILIANA
LS TORRES TUANAMA NUUITH
LS ARMAS CARIJANO ANGELICA
LS GARY BENDEZU PERALTA
LS RIOS FERNANDEZ DARIL EDUARDO
LS ESCAMILO ACEVEDO EDGARD MIGUEL
LS MEDRANO FLORES EDISON OMAR
CAS MARTINEZ VELASQUEZ JACKELIN SOLIMAR
LS PEREZ PONCE ESMAYDER
LS CORNEJO OBLITAS NICOLAS
CAS ULLOA REYES SANDY
CAS AGUILAR AGUILAR VIVIANA
LS NOLASCO QUISPE MARIA CLAUDIA
CAS LAVADO HUAMAN EMELY
LS YOSELIN GUEVARA FERNANDEZ
LS VILCHEZ RUIZ ANDREA BRISETH
LS CARHUAJULCA ULLOA JORGE
LS SANJINEZ NARVAJA RAFAELLA
CAS CASTAÑEDA CARRASCO SUSAN KAREN
LS MEDINA CAPCHA KARINA LETICIA
LS MENDOZA CUCHO OLGA LIZBETH
LS BAUTISTA VALDIVIA BRUSH BRAYAN
LS ROMERO RIVAS MARIA ISABEL
CAS BURGOS DIEGUEZ ANDRES JOSE
LS TAYA PINCHI ANGELICA
LS TICONA ROLDAN KELLY JULIZA
CAS CARDENAS TINTAYA MITCHELL
CAS HIDALGO SOTO MARCO ANTONIO
LS RIOS SALAZAR SUSANA
LS RAMOS BACIGALUPO VALERIA LUCIA
CAS ROJAS ALCANTARA MITZI AMANDA
LS CARDENAS MORALES JONATHAN
LS GARCIA PADILLA RAQUEL ROSARIO

[GRUPO 2 - CCO]
CAS GUERRERO VALLEJO ANGIE
CAS GARCIA MAYTA MERCEDES BELEN
LS AGUAYO AYQUIPA RAY ALAN
LS ANTESANO ALARCÓN FRANCISCO DAVID
CAS CASTERNOQUE TAMANI ELITA
LS GUTIERRES MEDINA SEBASTIAN RAFAEL
LS CRISPÍN RIVERA LINDAY ANTONELLA
CAS ROJAS ESQUIVEL, ESTELA AMERICA
LS CASTILLO CHERO JEAN FRANCO
LS MONTOYA CHUQUIJAJAS ERICK ANDERSON
LS MORALES RIVADENEYRA ANGEL JESUS
CAS YARASCA SUAREZ, JOSE SILVANO
LS ROMERO VILELA GRISELDA ARACELY
LS ROBLES MELENDEZ CARLOS EDUARDO
LS GAMAO MELO RENZO MARCELO
CAS CARAMANTIN GIL IVONE ROCIO
CAS DIAZ GUITIERREZ ROXANA
CAS FLORES FLORES MARIELA DE LOS ANGELES
LS HUAMAN CONDORI YSABEL
LS LOPEZ ZAIDA MARITZA
CAS FLORES MONTESINOS DIEGO
LS QUINTANA RETAMOSO JEAN CARLOS
LS VALDIVIA FLORES BRIGITTHE MARLEIN
LS ANTESANO ALARCÓN DANIEL
LS ANDREA YSABEL QUISPE POPE
LS LISSETH MILAGROS LAZARO HUAMAN
LS PILLIHUAMAN ASTUCURI HEYASELL
LS AGUILAR ALVARADO ANTHONY JUNIOR
LS TEJADA ORDINOLA CIELO MELISA
LS CAMARENA CHACCARA BRAYAN MANUEL
LS VARGAS MORALES ERIC JESÚS
LS PACOHUANCA MENDOZA GABY GLADYS
LS QUISPE CHAVEZ CLARA NICOLE
LS LINDA MARYLYN ALVARIÑO DIEGO
LS KHIARA BETZABETH SACA MORAN
LS RUTH MARIBEL QUISPE RUELAS
LS ANGGELO RODRIGO SOLIS AGUILAR
LS VARGAS SUCA SILVIA
LS AXEL JOSUE MENDOZA CHOQUE
LS ESTEBAN DAVID FLORES MENDIZABAL

[GRUPO 2 - CCO - ALFA (GPS, RADIO)]
CAS SERNAQUE AGUIRRE , BLANCA ESTHER
CAS PANTA ACOSTA VERENICE ROSALIA

[GRUPO 2 - SCV]
LS HUAMANI ALATA MATHEWS SEBASTIAN
LS MENDOZA OBREGON MARILYN JANET
LS ANTON JIMENEZ LIZANDRO MANFREDO
LS QUISPE CAJAS SERGIO
LS CRUZ PARILLO MARITSA
LS RIVERA PINZON MARIA ESTHER
CAS LUJAN TORRES MAISA SOLEDAD
LS VELARDE BURGA ELSA
LS PEREZ PONCE BRANDON IMANOL
LS RAMOS BAZAN CHELITA
LS MENDEZ FERNANDEZ DAVILA PATRICIA
LS PAUCAR SANCHEZ MARGORETH GERALDINE
LS CAMPOS ROSA MIRTHA
LS LOPES RIOS LUZ MARIA
LS LUQUE CORNEJO DIEGO ROBINSON
LS ROJAS TOLEDO PAMELA MILAGROS
LS PEDRO VELAZQUES ZUÑIGA
CAS GOMEZ PAREDES JENNY
CAS ROMAN HUERTAS GABRIELA SABRINA
LS OVIEDO POMA ILLIANOVICH OMAR
LS VILLEGAS SOTO JOHANNA ROCIO
LS ROJAS LUCAS PAOLA
LS MAMANI MAMANI GLADYS CATALINA
LS SURCA CRUZ ERICA
LS ALVARES ALVIS NYCOLL ANTHOANE
LS ALARCON BRAVO SEBASTIAN
LS ALVARADO RAMIÑOS RENZO
LS CRUZADO LLANOS PEDRO
LS LLANCA TELLO SHIRLEY LISSETH
CAS LAJO ROJAS DE CAMAC SANTA BEATRIZ
LS MARAVI INOCENTE LOURDES
LS QUISPE CHÁVEZ NICOLÁS BRYAN
LS BENAVIDES SALSEDO HECTOR ISRAEL
LS JUAREZ VICUÑA MARIA ALEXANDRA
LS AGUILAR PALOMINO DELIA
LS JUAN FELIX ALEXIS FUENTES
LS MENDEZ FERNANDEZ DAVILA TOMAS ALEXIS
LS VELA HUAPAYA ERICK ADINSON

[GRUPO 3 - CCO]
CAS GUERRERO VALLEJO ANGIE
CAS VASQUEZ ESTRELLA MARICELA
CAS ALVARADO ESTRADA GEIBBY EDELMIRA
CAS SEGUNDO HURTADO MARIAJOSE
LS CAMONES MENDOZA CARLOS GABRIEL
CAS MURILLO PONTE CARMELA REINA
CAS CARBAJAL BIRUNDE MAX JOEL
LS ALARCON TUCTO, LIZ SHAIRA
LS MORA HUAMANI DELINO ROCIO
LS MIRANDA YLLANES IVAN RICARDO
LS COTRINA RAMIREZ ANTUANET YURIKO
CAS PALOMINO GONZALES AXEL
LS RAFAEL SOTO RODRIGO ALEXANDER
LS HUAPAYA PALLARA JUANA ROSARIO
LS GUILLÉN RIOS DANIEL ALESSANDER
LS TIRADO AGUILAR MOISÉS AARON
LS AGUIRRE ROSALES, NELSON RAFAEL
LS HUARCAYA ARENAS ANGEL ANDRES
CAS AVILA CHIMOY EMILIA
LS VALDIVIA FLORES HUDSON RONALD
CAS ARELLANO GONZALES SAMANTHA
LS VILCHEZ SANCHEZ MONICA JUDITH
CAS CANALES ALARCON YANETH SONIA
LS PEREZ LOPEZ ELIZABETH KARIN
LS SULCA COLCA JUAN PABLO
LS TAQUIRI ALVAREZ JOEL SMITH
CAS FLORES SANCHEZ MARIA MILAGROS
LS GONZALES FLORES LIZZY JESSICA
LS MELGAREJO RODRÍGUEZ YOVER DAVID
LS INCA MARQUEZ GIANELLA MILADY
LS FLORES DELGADO EMMANUEL
LS MARY CARMEN BRIOSO DELGADO
LS HAROLL JAVIER ESTRADA AUQUE
LS JULIA BECERRA QUISPINGA
LS XIOMARA GIOHANNA MARQUEZ ARROYO
LS MARIA MILAGROS IDONE LOVERA
LS DIANA PAOLA MOLINA VALDIVIA
LS CAROL CHRIS STEFPANIE CUSICHE PEREZ
LS CARLOS GUSTAVO QUISPE GARAY

[GRUPO 3 - CCO - ALFA (GPS, RADIO)]
CAS MONTESINOS LOZANO, HAYDEE CONSUELO
CAS MANCHEGO SUCASAIRE, LUZ YRENE

[GRUPO 3 - SCV]
LS BUSTAMANTE ESPINOZA, CESAR BRUCE
LS CERDA GALINDO KARLA
LS PARRAGA VERGARA DIANA
LS PINEDO PIRO CRISTHIAN GABRIEL
CAS HERRERA JORGE GIOVANNY
LS DAVILA RIOS NATHALIE ZERIBETH
CAS MANRIQUE GOICOCHEA GISELLA
CAS PERALTA AREDO NAYFE SAFIRA
LS VIVAS BOHORQUEZ NICOLL MICHEL
LS PALACIOS GAMARRA ISSAC AARON
LS BUSTINZA LEON IVAN
LS ZURITA TORIBIO, NAYELI JAQUELINE
CAS ÑATO ESPIRITU, JESSICA YSABEL
LS FLORES TUESTA ALVARO
LS GARCIA HUAMAN, CARLA
LS MEJIA HUISA ANA MARIA
LS BAUTISTA MARAVI MISHELL NICOLLE
LS DOMINGUEZ RAMOS, ELIZABETH
LS CONTRERAS AMOTORO BETTY
LS YNFANTE QUISPE, ESTELA
LS SAN MIGUEL GUILLEN ELIZABETH
LS POLIVAKHIN ANDREY
CAS MARTINEZ HERRERA JERERMY SNAIDER
LS CAMAC LAJO ANGIE MICHELL
LS PALOMINO VILLEGAS ALISE
LS VILLALOBOS BARDALES LUIS GABRIEL
LS PAULINO HUAYTAN, MIGUEL
CAS ACHULLI RAMOS GLADYS
LS VARGAS CONDOR MARLITT ZARAI
LS YOVERA SANCHEZ KATHEEN
CAS ACOSTA GUTIERREZ MISAEL
LS SANDOVAL BRICEÑO JHOAN SAMIR
LS JIMENEZ ROJAS SUJEY
LS RIVERA RUIZ ALEJANDRA, FABIOLA
LS JULCA CARDOZO BRENDA MARELY
LS NOVOA MACHUCA GUSTAVO
LS SANTILLAN SAAVEDRA LORENA
LS TORRES ROJAS JORGE ALBERTO
"""

def parse_name(raw_string):
    # Expects "CAS LAST_NAME, FIRST_NAME" or "LS LAST_NAME FIRST_NAME"
    parts = raw_string.strip().split(' ', 1)
    if len(parts) < 2:
         return 'CAS', raw_string.strip(), ''
    
    regime = parts[0]
    remainder = parts[1].strip()
    
    if ',' in remainder:
        lname, fname = remainder.split(',', 1)
        return regime, fname.strip(), lname.strip()
    else:
        # Try to infer if no comma. Usually first two words are last names
        w = remainder.split(' ')
        if len(w) >= 3:
            return regime, " ".join(w[2:]), " ".join(w[:2])
        elif len(w) == 2:
            return regime, w[1], w[0]
        else:
            return regime, remainder, remainder

def seed_database():
    with app.app_context():
        print("Migrating schema if needed...")
        try:
            db.session.execute(text("ALTER TABLE workers ADD COLUMN allowed_shifts VARCHAR(20) DEFAULT 'M,T,N';"))
            print("Added allowed_shifts to workers table.")
        except Exception:
            db.session.rollback()
            
        try:
            db.session.execute(text("ALTER TABLE workers ADD COLUMN resignation_date DATE;"))
            print("Added resignation_date to workers table.")
        except Exception:
            db.session.rollback()
            
        db.session.commit()

        print("Clearing existing workers and schedule/attendance dependencies...")
        ScheduleEntry.query.delete()
        AttendanceRecord.query.delete()
        Worker.query.delete()
        db.session.commit()

        lines = RAW_DATA.strip().split('\n')
        
        current_section = ''
        current_area = ''
        current_group = None
        order = 1
        
        for line in lines:
            line = line.strip()
            if not line:
                continue
            
            if line.startswith('['):
                header = line[1:-1].strip()
                if 'JEFATURA' in header:
                    current_section = 'A'
                    current_area = 'JEFATURA'
                    current_group = None
                elif 'OBSERVATORIO' in header or 'VIDEO' in header:
                    current_section = 'B'
                    current_area = 'GESTIÓN DE VIDEO'
                    current_group = None
                elif 'SUPERVISORES' in header:
                    current_section = 'C'
                    current_area = 'SUPERVISORES'
                    current_group = None
                else:
                    current_section = 'D'
                    
                    if 'GRUPO 1' in header: current_group = 1
                    elif 'GRUPO 2' in header: current_group = 2
                    elif 'GRUPO 3' in header: current_group = 3
                    
                    if 'ALFA' in header:
                        current_area = 'ALFA'
                    elif 'SCV' in header:
                        current_area = 'SCV'
                    else:
                        current_area = 'CCO'
                continue
            
            # Sub-parse if supervisor with inline group: "CAS ORMEÑO ... -- GRUPO 1"
            inline_group = current_group
            if current_area == 'SUPERVISORES':
                if 'GRUPO 1' in line: inline_group = 1
                elif 'GRUPO 2' in line: inline_group = 2
                elif 'GRUPO 3' in line: inline_group = 3
                line = line.split('-')[0].strip()
            
            regime, fname, lname = parse_name(line)
            
            # User shift restrictions
            allowed_shifts = 'M,T,N'
            # Note: The prompt restricted specific names:
            if 'GUERRERO VALLEJO' in lname and 'ANGIE' in fname:
                allowed_shifts = 'T,N'
            elif 'VASQUEZ ESTRELLA' in lname and 'MARICELA' in fname:
                allowed_shifts = 'M,T'

            w = Worker(
                order_number=order,
                first_name=fname,
                last_name=lname,
                regime=regime,
                section=current_section,
                area=current_area,
                group_number=inline_group,
                status='activo',
                allowed_shifts=allowed_shifts
            )
            db.session.add(w)
            order += 1

        db.session.commit()
        print(f"Successfully seeded {order - 1} workers into the database.")
        
        # Set users assigned_groups appropriately from the supervisor list
        for user in User.query.filter_by(role='supervisor').all():
            if 'ORMEÑO' in user.full_name: user.assigned_group = 1
            if 'IÑAPE' in user.full_name: user.assigned_group = 2
            if 'BELLIDO' in user.full_name: user.assigned_group = 3
        db.session.commit()
        print("Updated Supervisor User accounts.")

if __name__ == '__main__':
    seed_database()
